version: '3'

services:
  app:
    build:
      context: ./
    container_name: tgmail_app
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
    networks:
      global_network:
      default:
    volumes:
      - tgmail-storage:/home/python/data

  redis:
    image: redis:alpine
    container_name: tgmail_redis
    restart: always
    networks:
      default:

networks:
  global_network:
    external: true
volumes:
  tgmail-storage:
